version: '3'

services:
  rustdesk-id:
    container_name: rustdesk-id
      # ports:
      #   - 21115:21115
      #   - 21116:21116
      #   - 21116:21116/udp
      #   - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r rustdesk-relay:21117
    volumes:
      - ${VOLUME_DIR}/rustdesk:/root
    networks:
      - traefik
    depends_on:
      - rustdesk-relay
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## TCP Routers
      - "traefik.tcp.routers.rustdesk-id1-rtr.entrypoints=rd5-tcp"
      - "traefik.tcp.routers.rustdesk-id1-rtr.rule=HostSNI(`rustdesk.${FQDN}`)"
      - "traefik.tcp.routers.rustdesk-id1-rtr.tls=true"
      ## Middlewares
      # - "traefik.tcp.routers.rustdesk-id1-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.tcp.routers.rustdesk-id1-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.tcp.routers.rustdesk-id1-rtr.middlewares=chain-oauth2-proxy@file" # OAuth 2.0
      ## TCP Services
      - "traefik.tcp.routers.rustdesk-id1-rtr.service=rustdesk-id1-svc"
      - "traefik.tcp.services.rustdesk-id1-svc.loadbalancer.server.port=21115"
      ##############################
      ###### Additional Ports ######
      ##############################
      ## TCP Routers
      - "traefik.tcp.routers.rustdesk-id2-rtr.entrypoints=rd6-tcp"
      - "traefik.tcp.routers.rustdesk-id2-rtr.rule=HostSNI(`rustdesk.${FQDN}`)"
      - "traefik.tcp.routers.rustdesk-id2-rtr.tls=true"
      ## Middlewares
      # - "traefik.tcp.routers.rustdesk-id2-rtr.middlewares=chain-no-auth@file" # No Authentication
      ## TCP Services
      - "traefik.tcp.routers.rustdesk-id2-rtr.service=rustdesk-id2-svc"
      - "traefik.tcp.services.rustdesk-id2-svc.loadbalancer.server.port=21116"
      ##############################
      ###### Additional Ports ######
      ##############################
      ## UDP Routers
      - "traefik.udp.routers.rustdesk-id3-rtr.entrypoints=rd6-udp"
      ## Middlewares
      # - "traefik.udp.routers.rustdesk-id3-rtr.middlewares=chain-no-auth@file" # No Authentication
      ## UDP Services
      - "traefik.udp.routers.rustdesk-id3-rtr.service=rustdesk-id3-svc"
      - "traefik.udp.services.rustdesk-id3-svc.loadbalancer.server.port=21116"
      ##############################
      ###### Additional Ports ######
      ##############################
      ## TCP Routers
      - "traefik.tcp.routers.rustdesk-id4-rtr.entrypoints=rd8-tcp"
      - "traefik.tcp.routers.rustdesk-id4-rtr.rule=HostSNI(`rustdesk.${FQDN}`)"
      - "traefik.tcp.routers.rustdesk-id4-rtr.tls=true"
      ## Middlewares
      # - "traefik.tcp.routers.rustdesk-id4-rtr.middlewares=chain-no-auth@file" # No Authentication
      ## TCP Services
      - "traefik.tcp.routers.rustdesk-id4-rtr.service=rustdesk-id4-svc"
      - "traefik.tcp.services.rustdesk-id4-svc.loadbalancer.server.port=21118"
      # ## URL: rustdesk.${FQDN}.com (Cloudflare)
      # - "traefik.tcp.routers.no-proxy-rtr.tls.certresolver=cloudflare"
      # - "traefik.tcp.routers.no-proxy-rtr.tls.domains[0].main=rustdesk.${FQDN}.com"
      # - "traefik.tcp.routers.no-proxy-rtr.tls.domains[0].sans=*.rustdesk.${FQDN}.com"
      # - "traefik.tcp.routers.no-proxy-rtr.rule=Host(`rustdesk.${FQDN}.com`) || Host(`www.rustdesk.${FQDN}.com`)"

  rustdesk-relay:
    container_name: rustdesk-relay
      # ports:
      #  - 21117:21117
      #  - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ${VOLUME_DIR}/rustdesk:/root
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## TCP Routers
      - "traefik.tcp.routers.rustdesk-relay1-rtr.entrypoints=rd7-tcp"
      - "traefik.tcp.routers.rustdesk-relay1-rtr.rule=HostSNI(`rustdesk.${FQDN}`)"
      - "traefik.tcp.routers.rustdesk-relay1-rtr.tls=true"
      ## Middlewares
      # - "traefik.tcp.routers.rustdesk-relay1-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.tcp.routers.rustdesk-relay1-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.tcp.routers.rustdesk-relay1-rtr.middlewares=chain-oauth2-proxy@file" # OAuth 2.0
      ## TCP Services
      - "traefik.tcp.routers.rustdesk-relay1-rtr.service=rustdesk-relay1-svc"
      - "traefik.tcp.services.rustdesk-relay1-svc.loadbalancer.server.port=21117"
      ##############################
      ###### Additional Ports ######
      ##############################
      ## TCP Routers
      - "traefik.tcp.routers.rustdesk-relay2-rtr.entrypoints=rd9-tcp"
      - "traefik.tcp.routers.rustdesk-relay2-rtr.rule=HostSNI(`rustdesk.${FQDN}`)"
      - "traefik.tcp.routers.rustdesk-relay2-rtr.tls=true"
      ## Middlewares
      # - "traefik.tcp.routers.rustdesk-relay2-rtr.middlewares=chain-no-auth@file" # No Authentication
      ## TCP Services
      - "traefik.tcp.routers.rustdesk-relay2-rtr.service=rustdesk-relay2-svc"
      - "traefik.tcp.services.rustdesk-relay2-svc.loadbalancer.server.port=21119"

networks:
  traefik:
    name: traefik
    external: true
    #run: docker network create traefik
