services:

  komodo-db:
    image: mongo
    container_name: komodo-db
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    networks:
      - traefik
    # ports:
    #   - 27017:27017
    volumes:
      - ${VOLUME_DIR}/komodo/db:/data/db
      - ${CONFIG_DIR}/komodo/db:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: komodo
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
  
  komodo:
    image: ghcr.io/mbecker20/komodo:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo
    restart: unless-stopped
    depends_on:
      - komodo-db
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    networks:
      - traefik
    # ports:
    #   - 9120:9120
    environment:
      KOMODO_HOST: https://komodo.${FQDN}
      KOMODO_DATABASE_ADDRESS: komodo-db:27017
      KOMODO_DATABASE_USERNAME: komodo
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      ## Core cache for repos for latest commit hash / contents
      - ${CONFIG_DIR}/komodo/repo-cache:/repo-cache
    labels:
      - komodo.skip= # Prevent Komodo from stopping with StopAllContainers
      - autoheal=true
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.komodo-rtr.entrypoints=websecure
      - traefik.http.routers.komodo-rtr.rule=Host(`komodo.$FQDN`)
      - traefik.http.routers.komodo-rtr.tls=true
      ## Middlewares
      # - traefik.http.routers.komodo-rtr.middlewares=chain-no-auth@file # No Authentication
      # - traefik.http.routers.komodo-rtr.middlewares=chain-basic-auth@file # Basic Authentication
      - traefik.http.routers.komodo-rtr.middlewares=chain-oauth2-proxy@file # OAuth 2.0
      ## HTTP Services
      - traefik.http.routers.komodo-rtr.service=komodo-svc
      - traefik.http.services.komodo-svc.loadbalancer.server.port=9120

  komodo-periphery:
    image: ghcr.io/mbecker20/periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo-periphery
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    networks:
      - traefik
    environment:
      PERIPHERY_REPO_DIR: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/repos
      PERIPHERY_STACK_DIR: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/stacks
      PERIPHERY_SSL_KEY_FILE: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/ssl/key.pem
      PERIPHERY_SSL_CERT_FILE: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/ssl/cert.pem
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/mbecker20/komodo/discussions/180.
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}

networks:
  traefik:
    name: traefik
    external: true
    #run: docker network create traefik