---
name: chatwoot

services:
  base: &base
    image: chatwoot/chatwoot:latest-ce
    container_name: chatwoot-app
    volumes:
      - ${VOLUME_DIR}/chatwoot/app:/app/storage
    networks:
      - traefik
  rails:
    <<: *base
    container_name: chatwoot-rails
    depends_on:
      - chatwoot-db
      - chatwoot-redis
    # ports:
    #   - '127.0.0.1:3000:3000'
    networks:
      - traefik
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.chatwoot-rtr.entrypoints=websecure
      - traefik.http.routers.chatwoot-rtr.rule=Host(`chatwoot.$FQDN`)
      - traefik.http.routers.chatwoot-rtr.tls=true
      ## Middlewares
      - traefik.http.routers.chatwoot-rtr.middlewares=chain-no-auth@file # No Authentication
      # - traefik.http.routers.chatwoot-rtr.middlewares=chain-basic-auth@file # Basic Authentication
      # - traefik.http.routers.chatwoot-rtr.middlewares=chain-oauth2-proxy@file # OAuth 2.0
      ## HTTP Services
      - traefik.http.routers.chatwoot-rtr.service=chatwoot-svc
      - traefik.http.services.chatwoot-svc.loadbalancer.server.port=3000

  sidekiq:
    <<: *base
    container_name: chatwoot-sidekiq
    depends_on:
      - chatwoot-db
      - chatwoot-redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    networks:
      - traefik
    restart: always

  chatwoot-db:
    image: pgvector/pgvector:pg16
    container_name: chatwoot-db
    restart: always
    # ports:
    #   - '127.0.0.1:5432:5432'
    volumes:
      - ${VOLUME_DIR}/chatwoot/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - traefik

  chatwoot-redis:
    image: redis:alpine
    container_name: chatwoot-redis
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    volumes:
      - ${VOLUME_DIR}/chatwoot/redis:/data
    # ports:
    #   - '127.0.0.1:6379:6379'
    networks:
      - traefik

  chatwoot-chat-widget:
    image: nginxinc/nginx-unprivileged:alpine
    container_name: chatwoot-chat-widget
    restart: unless-stopped
    volumes:
      - ./nginx/html:/tmp/templates/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - COMPANY_NAME=${COMPANY_NAME}
      - WEBSITE_TOKEN=${CHATWOOT_WEBSITE_TOKEN}
    entrypoint: >
      /bin/sh -c "
      mkdir -p /usr/share/nginx/html;
      envsubst '$$COMPANY_NAME $$FQDN $$WEBSITE_TOKEN' < /tmp/templates/html/chat.html.template > /usr/share/nginx/html/chat.html;
      exec nginx -g 'daemon off;'
      "
    # expose:
    #   - "8080"
    networks:
      - traefik
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.support-rtr.entrypoints=websecure
      - traefik.http.routers.support-rtr.rule=Host(`support.$FQDN`)
      - traefik.http.routers.support-rtr.tls=true
      ## Middlewares
      - traefik.http.routers.support-rtr.middlewares=chain-no-auth@file # No Authentication
      # - traefik.http.routers.support-rtr.middlewares=chain-basic-auth@file # Basic Authentication
      # - traefik.http.routers.support-rtr.middlewares=chain-oauth2-proxy@file # OAuth 2.0
      ## HTTP Services
      - traefik.http.routers.support-rtr.service=support-svc
      - traefik.http.services.support-svc.loadbalancer.server.port=8080

networks:
  traefik:
    name: traefik
    external: true
    #run: docker network create traefik