name: glances
services:

  glances:
    image: nicolargo/glances:latest
    restart: always
    pid: "host"
    privileged: true
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"
    environment:
      - TZ=${TZ}
      - GLANCES_OPT=-C /glances/conf/glances.conf -w
    labels:
      - autoheal=true
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.glances-rtr.entrypoints=websecure
      - traefik.http.routers.glances-rtr.rule=Host(`glances.$FQDN`)
      - traefik.http.routers.glances-rtr.tls=true
      ## Middlewares
      - traefik.http.routers.glances-rtr.middlewares=chain-no-auth@file # No Authentication
      # - traefik.http.routers.glances-rtr.middlewares=chain-basic-auth@file # Basic Authentication
      # - traefik.http.routers.glances-rtr.middlewares=chain-oauth2-proxy@file # OAuth 2.0
      ## HTTP Services
      - traefik.http.routers.glances-rtr.service=glances-svc
      - traefik.http.services.glances-svc.loadbalancer.server.port=61208
